### PR TITLE
Issue-219 Implement Move Functionality for File and Directory Management

### PR DESCRIPTION
**Pull request by Lazart**
Issue 219 [https://github.com/beam-cloud/beta9/issues/219](url)

This PR introduces the mv command to the CLI, enabling users to relocate files and directories within the same volume. 

Important note: the issue itself asks for example :
`beta9 volume mv ./file.txt ./artifacts/text-files/file.txt
`
But I gave myself the freedom to change this to :
`beta9 mv myvol/subdir/file.txt myvol/anotherdir/file.txt`
... and that is because other functions like :
`ls
cp
rm`
are doing in that manner so it made more sense for me to do it like that, but please request changes to 
do it in the requested manner if you still think that is the right way

ezgif-6-673f823f74

### CODE REVIEW

**Comment by jsun-m** [comment]
Did not forget about this. Just need to get protobuf validation into CI

**Comment by Lazart** [comment]
> Did not forget about this. Just need to get protobuf validation into CI #276

**Comment by jsun-m** [comment]
@Lazart can you rebase?

**Comment by Lazart** [comment]
> @Lazart can you rebase?

sure

**Comment by Lazart** [comment]
> @Lazart can you rebase?

@jsun-m branch updated

**Review by jsun-m — APPROVED** [review]
lgtm

**Pull request merged**
